import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { run } from './run.mjs';

const TAR = 'C:\\Windows\\System32\\tar.exe';
const IS_WIN = process.platform === 'win32';

function getShortPath(longPath) {
  return new Promise((resolve, reject) => {
    const psScript = '[Console]::OutputEncoding = [System.Text.Encoding]::UTF8; $p = $env:IRIS_LONGPATH; $fso = New-Object -ComObject Scripting.FileSystemObject; if (Test-Path -LiteralPath $p -PathType Container) { $item = $fso.GetFolder($p) } else { $item = $fso.GetFile($p) }; [Console]::Out.WriteLine($item.ShortPath)';
    const c = spawn('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', psScript], {
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, IRIS_LONGPATH: longPath },
    });
    const out = [];
    const err = [];
    c.stdout.on('data', (d) => out.push(d));
    c.stderr.on('data', (d) => err.push(d));
    c.on('close', (code) => {
      if (code !== 0) return reject(new Error(`getShortPath failed for ${longPath}: ${Buffer.concat(err).toString('utf8')}`));
      resolve(Buffer.concat(out).toString('utf8').trim());
    });
    c.on('error', reject);
  });
}

// Windows tar.exe (bsdtar) is invoked as a legacy ANSI console app: Node's
// spawn passes a Unicode command line, but the child reads it via
// GetCommandLineA(), which Windows converts to the system ANSI codepage
// (cp949 on this Korean-locale machine) before tar.exe ever sees it. Most
// Hangul syllables round-trip through cp949 losslessly, but this project's
// required folder name contains `〖`/`〗` (U+3016/U+3017), which cp949
// cannot represent -- they become literal '?' bytes that then match no real
// path, and tar.exe fails with "Error opening archive: Failed to open '...'"
// (root-caused 2026-09-11 via raw hex inspection of stderr).
//
// Fix: resolve the Windows 8.3 "short path" (e.g. `P03-IR~1`) for the
// nearest existing ancestor directory before invoking tar.exe. Short names
// are generated by silently dropping characters that don't fit -- including
// `〖`/`〗` -- so the resulting path is bracket-free and cp949-safe. The
// short path is looked up via a Node-spawned `powershell.exe` that reads the
// long Unicode path from an *environment variable* (not argv), since env
// vars reach the child via Node's Unicode environment block rather than
// argv, sidestepping the same ANSI-argv problem on the way in. PowerShell's
// own stdout must be forced to UTF-8 ([Console]::OutputEncoding) or the
// short name it prints back gets mangled the same way on the way out.
async function toTarSafePath(p) {
  if (!IS_WIN) return p;
  try {
    if (fs.existsSync(p)) return await getShortPath(p);
    // Not-yet-created path (e.g. a zip file tar.exe is about to write):
    // shorten the nearest existing ancestor and re-append the remaining
    // segment verbatim -- safe because trailing segments in this project
    // are always plain Hangul/ASCII filenames, never containing `〖`/`〗`.
    const parent = path.dirname(p);
    if (parent === p) return p; // reached the root; nothing more to shorten
    const shortParent = await toTarSafePath(parent);
    return path.join(shortParent, path.basename(p));
  } catch {
    // Short-path lookup unavailable (COM missing, 8.3 names disabled on the
    // volume, etc.) -- fall back to the original path so this function
    // stays safe to call unconditionally on any Windows machine.
    return p;
  }
}

export async function extractZip(zip, dest, { strip = 0 } = {}) {
  fs.mkdirSync(dest, { recursive: true });
  const safeZip = await toTarSafePath(zip);
  const safeDest = await toTarSafePath(dest);
  const args = ['-xf', safeZip, '-C', safeDest];
  if (strip) args.push('--strip-components', String(strip));
  const r = await run(TAR, args);
  if (r.code !== 0) throw new Error(`extract failed ${zip}: ${r.err}`);
}

// Fixed epoch every file/dir under `dir` is stamped with before zipping, so
// that two independent builds (different wall-clock times, different npm-ci
// runs) produce byte-identical zips as long as their *content* matches.
// zip entries carry each source file's mtime, so without this two builds of
// the same content differ byte-for-byte (verified 2026-09-11: same bytes,
// different mtimes -> different zip sha256; unify mtimes -> identical zip
// sha256). This is what makes verify/reproduce.mjs's manifest-hash
// comparison meaningful for zipDir-produced parts (face/dash/teamclaude).
const FIXED_MTIME = new Date('2026-01-01T00:00:00Z');

function normalizeMtimes(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      normalizeMtimes(p);
      fs.utimesSync(p, FIXED_MTIME, FIXED_MTIME);
    } else if (entry.isFile() || entry.isSymbolicLink()) {
      fs.utimesSync(p, FIXED_MTIME, FIXED_MTIME);
    }
  }
}

// normalizeMtimes (fs.utimesSync) only reaches atime/mtime via Win32
// SetFileTime -- it cannot touch a file's Windows *creation* time. bsdtar's
// zip writer embeds a Unix extended-timestamp extra field (tag 0x5455 "UT")
// in each entry's *local* header that carries a third stamp ("ctime"),
// which on Windows libarchive sources from that untouched creation time.
// Two sequential builds create files at different real wall-clock moments,
// so this ctime leaks ~seconds of build-to-build skew into otherwise
// identical zip bytes -- verified 2026-09-11 via byte-diff of two
// `--skip-download` builds' codex/teamclaude/face/dash zips: central
// directory + extracted content were byte-identical, only the local
// header's UT-extra ctime field differed. Fix: force every file/dir's
// creation time to the same fixed epoch too, via PowerShell (Node has no
// creation-time setter) before invoking tar.
async function normalizeCreationTimes(dir) {
  if (!IS_WIN) return;
  const psScript =
    '$ErrorActionPreference = "Stop"; ' +
    '$root = $env:IRIS_LONGPATH; ' +
    '$date = [DateTime]::Parse($env:IRIS_FIXED_MTIME).ToUniversalTime(); ' +
    'Get-ChildItem -LiteralPath $root -Recurse -Force | ForEach-Object { $_.CreationTimeUtc = $date }; ' +
    '(Get-Item -LiteralPath $root -Force).CreationTimeUtc = $date';
  await new Promise((resolve, reject) => {
    const c = spawn('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', psScript], {
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, IRIS_LONGPATH: dir, IRIS_FIXED_MTIME: FIXED_MTIME.toISOString() },
    });
    const err = [];
    c.stderr.on('data', (d) => err.push(d));
    c.on('close', (code) => {
      if (code !== 0) return reject(new Error(`normalizeCreationTimes failed for ${dir}: ${Buffer.concat(err).toString('utf8')}`));
      resolve();
    });
    c.on('error', reject);
  });
}

export async function zipDir(dir, zipPath) {
  fs.mkdirSync(path.dirname(zipPath), { recursive: true });
  normalizeMtimes(dir);
  fs.utimesSync(dir, FIXED_MTIME, FIXED_MTIME);
  await normalizeCreationTimes(dir);
  const safeDir = await toTarSafePath(dir);
  const safeZipPath = await toTarSafePath(zipPath);
  const r = await run(TAR, ['-a', '-cf', safeZipPath, '-C', safeDir, '.']);
  if (r.code !== 0) throw new Error(`zip failed ${dir}: ${r.err}`);
}
